In [33]:
import numpy as np
import matplotlib.pyplot as plt

In [34]:
f = lambda x: x[0]**2 + 5*x[1]**2
fp = lambda x: np.array([2*x[0], 10*x[1]])

In [35]:
def grad_des(x0, n=10):
    if n == 0:
        return x0
    else:
        x1 = x0 - alpha * fp(x0)
        return grad_des(x1, n=n-1)

In [36]:
# Gradient descent

alpha = 0.15

x0 = np.array([2, 1])
n = 10

x = x0
xs_GD = []
xs_GD.append(x0)
for i in range(1, n+1):
    x = x - alpha * fp(x)
    print(x)
    xs_GD.append(x)
x_GD = x

[ 1.4 -0.5]
[0.98 0.25]
[ 0.686 -0.125]
[0.4802 0.0625]
[ 0.33614 -0.03125]
[0.235298 0.015625]
[ 0.1647086 -0.0078125]
[0.11529602 0.00390625]
[ 0.08070721 -0.00195312]
[0.05649505 0.00097656]


In [37]:
xs_GD

[array([2, 1]),
 array([ 1.4, -0.5]),
 array([0.98, 0.25]),
 array([ 0.686, -0.125]),
 array([0.4802, 0.0625]),
 array([ 0.33614, -0.03125]),
 array([0.235298, 0.015625]),
 array([ 0.1647086, -0.0078125]),
 array([0.11529602, 0.00390625]),
 array([ 0.08070721, -0.00195312]),
 array([0.05649505, 0.00097656])]

In [23]:
# Adam

alpha = 0.15
beta1 = 0.9
beta2 = 0.999
eps = 0.0

x0 = x0 = np.array([2, 1])
n = 10

m = 0.0
v = 0.0
m_hat = 0.0
v_hat = 0.0
x = x0
for i in range(1, n+1):
    m = beta1*m + (1-beta1)*fp(x)
    v = beta2*v + (1-beta2)*fp(x)**2
    m_hat = m / (1-beta1**i)
    v_hat = v / (1-beta2**i)
        
    x = x - alpha / (np.sqrt(v_hat) + eps) * m_hat
    
    print(x)
x_Adam = x

[1.85 0.85]
[1.70041816 0.70112266]
[1.5515864  0.55445574]
[1.40388169 0.41142542]
[1.25773005 0.27385646]
[1.11360994 0.1439941 ]
[0.97205476 0.02444214]
[ 0.83365359 -0.08203054]
[ 0.69904963 -0.17282561]
[ 0.56893541 -0.24592352]


In [24]:
x_GD

array([0.05649505, 0.00097656])

In [25]:
x_Adam

array([ 0.56893541, -0.24592352])

In [26]:
f(x_GD)

0.0031964590234865114

In [28]:
f(x_Adam)

0.626079395603792